site_name: "CBFpy"
site_description: "Control Barrier Functions in Python"
site_url: "https://danielpmorton.github.io/cbfpy"
repo_url: "https://github.com/danielpmorton/cbfpy"
repo_name: "danielpmorton/cbfpy"
site_dir: "site"

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: true
          inherited_members: true
          members_order: "source"

nav:
- Home: 
  - index.md
  - Guides:
    - Virtual Environment: pyenv.md
  - API Highlights:
    - "CBF": api/cbf.md
    - "CLF-CBF": api/clf_cbf.md
    - "CBF Config": api/cbf_config.md
    - "CLF-CBF Config": api/clf_cbf_config.md
- API Reference:
  - CBFs:
    - "CBF": api/cbf.md
    - "CLF-CBF": api/clf_cbf.md
  - Configuration:
    - "CBF Config": api/cbf_config.md
    - "CLF-CBF Config": api/clf_cbf_config.md
  - Environments:
    - "Base Env": api/base_env.md
    - "Cruise Control Env": api/car_env.md
    - "Point Robot Envs": api/point_robot_envs.md
    - "Drone Env": api/drone_env.md
    - "Manipulator Envs": api/arm_envs.md
  - Examples:
    - "Adaptive Cruise Control": api/acc_demo.md
    - "Point Robot: Safe Set": api/point_robot_demo.md
    - "Point Robot: Obstacle Avoidance": api/point_robot_obstacle_demo.md
    - "Drone Obstacle Avoidance": api/drone_demo.md
    - "Manipulator Joint Limits": api/joint_limits_demo.md

theme:
  name: material
  logo: logo.svg
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  favicon: favicon.png

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
